### ISSUE TITLE
Needs new version tagged

### ISSUE THREAD

**Issue by vicgonvt** [nullthoughts/laravel-data-sync#23]
**Describe the bug**
When installing through composer, it pulls in v1.0 which is still using `str_studly()` which is removed in Laravel 6.

**To Reproduce**
1. In terminal, `composer require distinctm/laravel-data-sync`
2. This pulls in v1.0

**Laravel (please complete the following information):**
 - Host OS: Mac OS X
 - Version 6.11

**Comment by nullthoughts** [comment]
Thanks! v1.1.0 released
